# Configure sensors
PLATFORM_HAS_WIND_SENSOR=0
PLATFORM_HAS_TEMPERATURE_SENSOR=0
PLATFORM_HAS_PRESSURE_SENSOR=0
PLATFORM_HAS_RAIN_SENSOR=0
PLATFORM_HAS_BATT_SENSOR=0

# Other peripherals
PLATFORM_HAS_LEDS=1
PLATFORM_HAS_BUTTONS=1

#########################################################################
ifeq ($(PLATFORM_HAS_WIND_SENSOR), 1)
	CFLAGS += -DPLATFORM_HAS_WIND_SENSOR
endif	
ifeq ($(PLATFORM_HAS_TEMPERATURE_SENSOR), 1)
	CFLAGS += -DPLATFORM_HAS_TEMPERATURE_SENSOR
endif	
ifeq ($(PLATFORM_HAS_PRESSURE_SENSOR), 1)
	CFLAGS += -DPLATFORM_HAS_PRESSURE_SENSOR
endif	
ifeq ($(PLATFORM_HAS_RAIN_SENSOR), 1)
	CFLAGS += -DPLATFORM_HAS_RAIN_SENSOR
endif
ifeq ($(PLATFORM_HAS_BATT_SENSOR), 1)
	CFLAGS += -DPLATFORM_HAS_BATT_SENSOR
endif		
ifeq ($(PLATFORM_HAS_LEDS), 1)
	CFLAGS += -DPLATFORM_HAS_LEDS
endif	
ifeq ($(PLATFORM_HAS_BUTTONS), 1)
	CFLAGS += -DPLATFORM_HAS_BUTTONS
endif	

#########################################################################

CONTIKI=../..

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"


# variable for root Makefile.include
WITH_UIP6=1
# for some platforms
UIP_CONF_IPV6=1

# variable for this Makefile
# configure CoAP implementation (3|6|7)
WITH_COAP=7

# must be CFLAGS not variables
# minimal-net does not support RPL, avoid redefine warnings
ifneq ($(TARGET), minimal-net)
#	ifneq ($(TARGET), avr-atmega128rfa1)
		UIP_CONF_RPL=0
		CFLAGS += -DUIP_CONF_IPV6_RPL=0
#	endif
endif

# linker optimizations
CFLAGS += -ffunction-sections
LDFLAGS += -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__

# REST framework, requires WITH_COAP
ifeq ($(WITH_COAP), 7)
${info INFO: compiling with CoAP-07}
CFLAGS += -DWITH_COAP=7
CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0
APPS += er-coap-07
else ifeq ($(WITH_COAP), 6)
${info INFO: compiling with CoAP-06}
CFLAGS += -DWITH_COAP=6
CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0
APPS += er-coap-06
else ifeq ($(WITH_COAP), 3)
${info INFO: compiling with CoAP-03}
CFLAGS += -DWITH_COAP=3
CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0
APPS += er-coap-03
else
${info INFO: compiling with HTTP}
CFLAGS += -DWITH_HTTP
CFLAGS += -DREST=http_rest_implementation
CFLAGS += -DUIP_CONF_TCP=1
APPS += rest-http-engine
endif

APPS += erbium


include $(CONTIKI)/Makefile.include